config/routes.rb
Rails.application.routes.draw do

  get 'nb10000apis/mujin_all'
  resources :products
  devise_scope :user do 
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # sign_up/registration
    get "sign_out", :to => "users/sessions#destroy" 
  end

  devise_for :users

  get 'landings/Home'
  get '/showmap', to: 'landings#ShowMap'
  get '/showsalespoint', to: 'landings#ShowSalesPoint'
  root 'landings#Home'
  
  resources :sales_points
  post '/add_sales_product_relation',  to: 'sales_points#add_sales_product_relation'
  post '/edit_sales_product_relation', to: 'sales_points#edit_sales_product_relation'
  delete '/delete_sales_product_relation', to: 'sales_points#delete_sales_product_relation'

  # API
  get 'apis/salespoints'
  get 'apis/salesdistance'
  get 'apis/performlogin'
  get 'apis/performapikeylogin'
  get 'apis/changepassword'
  post 'apis/submitnewprofile'
  #get 'apis/submitnewprofile'
  post 'apis/updatestock'
  get 'apis/currentstockallsp'
  get 'apis/currentstocksp'
  #get 'apis/submitnewprofile'
  get 'apis/reg_sp'
  post 'apis/reg_product'
  get 'apis/reg_product'
  get 'apis/sp_rel_reg'
  get 'apis/sp_owned'
  
  get 'nb10000apis/salesdistance'
  get 'nb10000apis/reg_product'
  get 'nb10000apis/reg_market'

end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  #before_action :authenticate_user!

  def Home
    @page = 1
    @sales_points = SalesPoint.all
  end

  def ShowMap
    @page = 2
    @googleapikey = ENV['GOOGLE_API_KEY']
    @sales_points = SalesPoint.all
    render 'Home'
  end

  def ShowSalesPoint
    @sales_point = SalesPoint.find(params['id'])
    @editable = false
    @googleapikey = ENV['GOOGLE_API_KEY']
    sprs = SalesProductRelation.where("sales_point_id=?",@sales_point.id)
    @product_choices = {}
    render 'sales_points/show'
  end

end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/views/landings/Home.html.erb
<% provide(:title, "ホーム") %>
<ul class="nav nav-tabs mt-1" style="margin-left: -12px; margin-right: -12px">
  <li class="nav-item">
    <% if @page == 1 %>
        <a class="nav-link active" aria-current="page" href="<%= root_path %>">無人販売一覧</a>
    <% else %>
        <a class="nav-link" aria-current="page" href="<%= root_path %>">無人販売一覧</a>
    <% end %>
  </li>
  <li class="nav-item">
    <% if @page == 2 %>
        <a class="nav-link active" aria-current="page" href="<%= showmap_path %>" >🌏地図</a>
    <% else %>
        <a class="nav-link" aria-current="page" href="<%= showmap_path %>" >🌏地図</a>
    <% end %>
  </li>
</ul>
<div class="row bg-white border-start border-end border-bottom rounded-bottom rounded-5">
    <div class="col-12">
        <% if @page == 1 %>
            <%= render 'index' %>
        <% else %>
            <%= render 'map' %>
        <% end %>
    </div>
</div>

app/views/landings/_index.html.erb
<table class="table table-hover">
  <thead>
    <tr class="text-center">
      <th scope="col">№</th>
      <th scope="col">無人名</th>
      <th scope="col">最終更新時刻</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% counter = 0 %>
    <% @sales_points.each do |sales_point| %>
      <% counter += 1 %>
      <tr>
        <th scope="row" class="text-center"><%= counter %></th>
        <td><%=sales_point.name %></td>
        <td class="text-center"><%= sales_point.updated_at %></td>
        <td>
            <%= link_to '詳細', showsalespoint_path(:id => sales_point.id), class:"btn btn-primary btn-sm" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/landings/_map.html.erb
<div id="map" style="height: 600px;"></div> 
<script
    src="https://maps.googleapis.com/maps/api/js?key=<%= @googleapikey %>&callback=initMap&libraries=&v=weekly"
    async>
</script>
<script>
  let map;

  function initMap() {
    map = new google.maps.Map(document.getElementById("map"), {
      center: { lat: 34.96044797500092, lng: 138.4044472577484 },
      zoom: 15,
    });
    <% @sales_points.each do |sales_point| %>
      const spLatLng<%=sales_point.id%> = { lat: <%=sales_point.lat%>, lng: <%=sales_point.lon%> };
      new google.maps.Marker({
        position: spLatLng<%=sales_point.id%>,
        map,
        title: "<%=sales_point.description%>",
        });
    <% end %>
   
  }

</script>