config/routes.rb
Rails.application.routes.draw do

  get 'nb10000apis/mujin_all'
  resources :products
  devise_scope :user do 
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # sign_up/registration
    get "sign_out", :to => "users/sessions#destroy" 
  end

  devise_for :users

  get 'landings/Home'
  get '/showmap', to: 'landings#ShowMap'
  get '/showsalespoint', to: 'landings#ShowSalesPoint'
  root 'landings#Home'
  
  resources :sales_points
  post '/add_sales_product_relation',  to: 'sales_points#add_sales_product_relation'
  post '/edit_sales_product_relation', to: 'sales_points#edit_sales_product_relation'
  delete '/delete_sales_product_relation', to: 'sales_points#delete_sales_product_relation'

  # API
  get 'apis/salespoints'
  get 'apis/salesdistance'
  get 'apis/performlogin'
  get 'apis/performapikeylogin'
  get 'apis/changepassword'
  post 'apis/submitnewprofile'
  #get 'apis/submitnewprofile'
  post 'apis/updatestock'
  get 'apis/currentstockallsp'
  get 'apis/currentstocksp'
  #get 'apis/submitnewprofile'
  get 'apis/reg_sp'
  post 'apis/reg_product'
  get 'apis/reg_product'
  get 'apis/sp_rel_reg'
  get 'apis/sp_owned'
  
  get 'nb10000apis/salesdistance'
  get 'nb10000apis/reg_product'
  get 'nb10000apis/reg_market'

end

app/models/sales_point.rb
class SalesPoint < ApplicationRecord
  belongs_to :user
  has_many :sales_product_relations, dependent: :destroy
end

app/controllers/sales_points_controller.rb
class SalesPointsController < ApplicationController
  before_action :set_sales_point, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /sales_points or /sales_points.json
  def index
    @sales_points = current_user.sales_points #SalesPoint.all
  end

  # GET /sales_points/1 or /sales_points/1.json
  def show
    @googleapikey = ENV['GOOGLE_API_KEY']
    @editable = true
    sprs = SalesProductRelation.where("sales_point_id=?",@sales_point.id)
    @product_choices = {}
    current_user.products.each do |product|
      exist = false
      sprs.each do |spr|
        if product.id == spr.product_id
          exist = true
        end
      end
      if exist == false 
        @product_choices[product.name] = product.id
      end
    end
  end

  # GET /sales_points/new
  def new
    @sales_point = SalesPoint.new
    @sales_product_relation = SalesProductRelation.new
    @googleapikey = ENV['GOOGLE_API_KEY']
  end

  # GET /sales_points/1/edit
  def edit
    @googleapikey = ENV['GOOGLE_API_KEY']
  end

  # POST /sales_points or /sales_points.json
  def create
    @sales_point = SalesPoint.new(sales_point_params)
    respond_to do |format|
      if @sales_point.save
        format.html { redirect_to @sales_point, notice: "Sales point was successfully created." }
        format.json { render :show, status: :created, location: @sales_point }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sales_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales_points/1 or /sales_points/1.json
  def update
    respond_to do |format|
      if @sales_point.update(sales_point_params)
        format.html { redirect_to @sales_point, notice: "Sales point was successfully updated." }
        format.json { render :show, status: :ok, location: @sales_point }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sales_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales_points/1 or /sales_points/1.json
  def destroy
    @sales_point.destroy
    respond_to do |format|
      format.html { redirect_to sales_points_url, notice: "Sales point was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def add_sales_product_relation
    sales_point_id = sales_product_relation_params['sales_point_id']
    product_id = sales_product_relation_params['product_id']
    price = sales_product_relation_params['price'].to_d

    @sales_point = SalesPoint.find(sales_point_id)
    @product = Product.find(product_id)
    if price <= 0 
      price = @product.dprice
    end

    SalesProductRelation.create(sales_point_id: sales_point_id, product_id: product_id, price: price)
    redirect_to @sales_point
  end

  def edit_sales_product_relation
    sales_product_relation = SalesProductRelation.find(sales_product_relation_params['id'])
    @sales_point = SalesPoint.find(sales_product_relation.sales_point_id)
    sales_product_relation.update(price: sales_product_relation_params['price'].to_d, product_id: sales_product_relation_params['product_id'].to_i)
    redirect_to @sales_point
  end
  
  def delete_sales_product_relation
    sales_product_relation = SalesProductRelation.find(params[:id])
    @sales_point = SalesPoint.find(sales_product_relation.sales_point_id)
    sales_product_relation.destroy
    redirect_to @sales_point
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sales_point
      @sales_point = SalesPoint.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sales_point_params
      params.require(:sales_point).permit(:name, :description, :user_id, :status, :lat, :lon, :capacity)
    end

    def sales_product_relation_params
      params.require(:sales_product_relation).permit(:price, :product_id, :sales_point_id, :id)
    end

end

app/helpers/sales_points_helper.rb
module SalesPointsHelper
end

app/views/sales_points/_form.html.erb
<%= form_with(model: sales_point) do |form| %>
  <% if sales_point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sales_point.errors.count, "error") %> prohibited this sales_point from being saved:</h2>

      <ul>
        <% sales_point.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field input-group">
    <%= form.label :name,"名前" , class:'input-group-prepend col-3 input-group-text', id:'basic-addon1' %>
    <%= form.text_field :name, class:'form-control' %>
  </div>

  <div class="field input-group mt-1">
    <%= form.label :description,"詳細", class:'input-group-prepend col-3 input-group-text' %>
    <%= form.text_area :description, class:'form-control' %>
  </div>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="field input-group mt-1">
    <%= form.label :capacity,'Cap', class:'input-group-prepend col-3 input-group-text' %>
    <%= form.number_field :capacity, class: 'form-control' %>
    <%= form.label :status,"状態", class:'input-group-text' %>
    <%= form.select :status, {'無効': 0, '有効': 1}, {class:'form-control', required: true} %>
  </div>

  <div class="field input-group mt-1">
    <%= form.label :lat, class:'input-group-prepend col-3 input-group-text' %>
    <%= form.text_field :lat, class:'form-control', id: 'latlongclicked' %>
  </div>

  <div class="field input-group mt-1">
    <%= form.label :lon, class:'input-group-prepend col-3 input-group-text' %>
    <%= form.text_field :lon, class:'form-control', id: 'lonlongclicked'  %>
  </div>

  <div class="actions d-grid gap-2">
    <%= form.submit "登録💾", class: "btn btn-outline-info mt-1" %>
  </div>
<% end %>

app/views/sales_points/edit.html.erb
<div class="row">
    <div class="col-5">
        <div class="card shadow">
            <div class="card-header text-center">
                <h2>販売店編集✏️</h2>
            </div>
            <div class="card-body">
                <%= render 'form', sales_point: @sales_point %>
            </div>
            <div class="card-footer">
                <%= link_to '🔙戻る', sales_points_path, class:"btn btn-outline-primary" %>
                <%= link_to '👁‍🗨表示', @sales_point, class:"btn btn-outline-success" %>
            </div>
        </div>
    </div>
    <div class="col-7">
        <div id="map" class="shadow"></div>
        <style>
            #map{
                height: 100%;
            }
        </style>
        
        <script>
            let map;
            function initMap() {
            const myLatLng = { lat: <%=@sales_point.lat%>, lng: <%=@sales_point.lon%> };
            map = new google.maps.Map(document.getElementById("map"), {
                center: myLatLng,
                zoom: 15,
            });
            
            new google.maps.Marker({
            position: myLatLng,
            map,
            title: "<%=@sales_point.description%>",
            });

            google.maps.event.addListener(map, 'click', function(event){
                document.getElementById('latlongclicked').value = event.latLng.lat();
                document.getElementById('lonlongclicked').value = event.latLng.lng();
            });
            
            }
        </script>
        <script
        src="https://maps.googleapis.com/maps/api/js?key=<%= @googleapikey %>&callback=initMap"
        async defer>
        
        </script>
    </div>
</div>

app/views/sales_points/index.html.erb
<div class="row bg-white border rounded-bottom rounded-3 text-center shadow">
  <div class="col-12">
      <h2>販売店</h2>
  </div>
</div>  
<div class="row bg-white border rounded-bottom rounded-3 mt-1 shadow">
  <div class="col-12">
    <table class="table table-hover">
      <thead>
        <tr class="text-center">
          <th scope="col">名前</th>
          <th scope="col">詳細</th>
          <th scope="col">状態</th>
          <th scope="col">Lat</th>
          <th scope="col">Lon</th>
          <th scope="col">Max (個)</th>
          <th scope="col" colspan="3">操作</th>
        </tr>
      </thead>

      <tbody>
        <% @sales_points.each do |sales_point| %>
          <tr>
            <td><%= sales_point.name %></td>
            <td><%= sales_point.description %></td>
            <td class="text-center">
            <% case sales_point.status %>
              <% when 0 then %>
                無効
              <% when 1 then %>
                有効
              <% else %>
                Undefined
            <% end %>
            </td>
            <td class="text-end"><%= sales_point.lat %></td>
            <td class="text-end"><%= sales_point.lon %></td>
            <td class="text-center"><%= sales_point.capacity %></td>
            <td class="text-center"><%= link_to '表示', sales_point, class: "btn btn-sm btn-outline-success" %></td>
            <td class="text-center"><%= link_to '編集', edit_sales_point_path(sales_point), 'data-no-turbolink' => true, class: "btn btn-sm btn-outline-info" %></td>
            <td class="text-center"><%= link_to '削除', sales_point, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-danger" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to '新規販売ポイント', new_sales_point_path, class: "btn btn-primary mb-1 mt-0"%>
  </div>
</div>

app/views/sales_points/new.html.erb
<div class="row">
    <div class="col-5">

        <div class="card shadow">
            <div class="card-header text-center">
                <h2>新規販売店🏪</h2>
            </div>
            <div class="card-body">
                <%= render 'form', sales_point: @sales_point %>
            </div>
            <div class="card-footer">
                <%= link_to '🔙 キャンセル', sales_points_path, class: "btn btn-outline-primary" %>
            </div>
        </div>
    </div>
    <div class="col-7 border">
        <div id="map" class="shadow"></div>
        <style>
            #map{
                height: 100%;
            }
        </style>
        
        <script
        src="https://maps.googleapis.com/maps/api/js?key=<%= @googleapikey %>&callback=initMap&libraries=&v=weekly"
        async>
        </script>
    </div>
</div>

<script>
  let map;

  function initMap() {
    map = new google.maps.Map(document.getElementById("map"), {
      center: { lat: 34.96044797500092, lng: 138.4044472577484 },
      zoom: 15,
    });
    google.maps.event.addListener(map, 'click', function(event){
      document.getElementById('latlongclicked').value = event.latLng.lat();
      document.getElementById('lonlongclicked').value = event.latLng.lng();
      
    });
  }
</script>

app/views/sales_points/show.html.erb
<div class="row bg-white border rounded-bottom rounded-3 shadow">
  <div class="col-12 border">
    <div class="row">
      <div class="col-12 text-center">
        <h2>販売店</h2>
      </div>
    </div>
    <div class="row bg-light text-center">
      <div class="col-1 border-top border-start border-bottom text-start">
        <% if @editable %>
          <%= link_to '🔙戻る', sales_points_path, class:"btn btn-outline-primary btn-sm" %>
        <% else %>
          <%= link_to '🔙戻る', root_path, class:"btn btn-outline-primary btn-sm" %>
        <% end %>
      </div>
      <div class="col-2 border-top border-end border-bottom">
        名前
      </div>
      <div class="col-4 border">
       詳細
      </div>
      <div class="col-1 border">
       状態
      </div>
      <div class="col-3 border">
       場所
      </div>
      <div class="col-1 border">
        負荷容量(個)
      </div>
    </div>
    <div class="row">
      <div class="col-3 border">
        <% if @editable %>
          <%= link_to '編集', edit_sales_point_path(@sales_point), class:"btn btn-outline-success btn-sm" %>
        <% end %>
        <%= @sales_point.name %>
      </div>
      <div class="col-4 border">
        <%= @sales_point.description %>
      </div>
      <div class="col-1 border text-center">
        <% case @sales_point.status %>
          <% when 0 then %>
            無効
          <% when 1 then %>
            有効
          <% else %>
            定義がない
        <% end %>
      </div>
      <div class="col-2 text-center border-top border-start border-bottom">
        <%= @sales_point.lat %>, <%= @sales_point.lon %>
      </div>
      <div class="col-1 d-grid gap-2 text-center border-top border-end border-bottom">
        <button class="btn btn-outline-primary btn-sm" data-bs-toggle="modal" data-bs-target="#mapModal<%=@sales_point.id%>">地図📍</button>
      </div>
      <div class="col-1 border text-center">
        <%= @sales_point.capacity %>
      </div>
    </div>
  </div>
</div>
<div class="row bg-white border rounded-bottom rounded-3 shadow">
  <div class="col-12">
    <div class="row">
      <div class="col-12 text-center border-bottom">
        <h3>製品一覧</h3>
      </div>
    </div>
    <div class="row border-bottom bg-light">
      <div class="col-2 text-center">
        <strong>製品名</strong>
      </div>
      <div class="col-4 border-start text-center">
        <strong>詳細</strong>
      </div>
      <div class="col-2 border-start text-center">
        <strong>価格</strong>
      </div>
      <div class="col-1 border-start text-center">
        <strong>状態</strong>
      </div>
      <div class="col-1 border-start text-center">
        <strong>在庫</strong>
      </div>
      <div class="col-2 border-start text-center">
        <strong></strong>
      </div>
    </div>
    <% counter = 1 %>
    <% @sales_point.sales_product_relations.each do |sales_product_relation| %>
      <% product = Product.find(sales_product_relation.product_id) %>
      <div class="row border-bottom">
        <div class="col-2">
          <%= product.name %>
        </div>
        <div class="col-4 border-start">
          <%= product.description %>
        </div>
        <div class="col-2 border-start text-end">
          <%= sales_product_relation.price %>
        </div> 
        <div class="col-1 border-start text-center">
          <% case product.status %>
            <% when 0 then %>
              製造中止
            <% when 1 then %>
              販売中
            <% else %>
              undefined
          <% end %>
        </div>
        <div class="col-1 border-start text-center">
          n/a
        </div>
        <div class="col-2 border-start text-center">
          <% if @editable %>  
            <td><button class="btn btn-outline-info btn-sm" data-bs-toggle="modal" data-bs-target="#productedit<%= sales_product_relation.id %>">編集</button></td>
            <td class="text-center"><%= link_to '削除', delete_sales_product_relation_path(:id => sales_product_relation.id), class: "btn btn-sm btn-outline-danger", role: "button", method: :delete, data: { confirm: "Are you sure?" } %></td>
          <% else %>
            <td><button class="btn btn-outline-warning btn-sm" data-bs-toggle="modal" data-bs-target="#productedit<%= sales_product_relation.id %>">写真</button></td>
          <% end %>
        </div>
      </div>
    <% end %>
    <div class="row mt-1 mb-1">
      <div class="col-2">
        <% if @product_choices.count > 0 && @editable %>
          <button class="btn btn-outline-primary btn-sm" data-bs-toggle="modal" data-bs-target="#productadd">製品追加</button>
        <% end %>
      </div>
      <div class="col-10">
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="mapModal<%=@sales_point.id%>" tabindex="-1" aria-labelledby="mapModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="mapModalLabel"><%=@sales_point.name%></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div id="map" ></div>
        <style>
            #map{
                height: 300px;
            }
        </style>
        
        <script
        src="https://maps.googleapis.com/maps/api/js?key=<%= @googleapikey %>&callback=initMap&libraries=&v=weekly"
        async>
        </script>
      </div>
    </div>
  </div>
</div>

<script>
  let map;
  function initMap() {
    const myLatLng = { lat: <%=@sales_point.lat%>, lng: <%=@sales_point.lon%> };
    map = new google.maps.Map(document.getElementById("map"), {
      center: myLatLng,
      zoom: 15,
      mapTypeId: "terrain",
    });
    new google.maps.Marker({
    position: myLatLng,
    map,
    title: "<%=@sales_point.description%>",
    });
  }
</script>

<div class="modal fade" id="productadd" tabindex="-1" aria-labelledby="productAddLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="mapModalLabel">製品追加</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">

        <%= form_for(:sales_product_relation, url: add_sales_product_relation_path) do |f| %>
          <div class="field input-group mt-1">
            <%= f.label :price, "価格",class:'input-group-prepend col-3 input-group-text' %>
            <%= f.text_field :price, class:'form-control' %>
            <span class="input-group-text">💱</span>
            <%= f.label :product_id,"商品名", class:'input-group-text' %>
            <%= f.select :product_id, @product_choices, {class:'form-control', required: true} %>
          </div>

          <%= f.hidden_field :sales_point_id, value: @sales_point.id %>

          <div class="actions d-grid gap-2 mt-1">
            <%= f.submit "追加", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% modif_product = {} %>
<% @sales_point.sales_product_relations.each do |sales_product_relation| %>
  <% modif_product[sales_product_relation.id] = {} %>
  <% product = Product.find(sales_product_relation.product_id) %>
  <% selected_product = {} %>
  <% selected_product[product.name] = product.id %>
  <% modif_product[sales_product_relation.id][product.name] = product.id %>
  <% @product_choices.each do |key, value| %>
    <% modif_product[sales_product_relation.id][key] = value %>
  <% end %>
  <div class="modal fade" id="productedit<%= sales_product_relation.id %>" tabindex="-1" aria-labelledby="productEditLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <% if @editable %>
            <h5 class="modal-title" id="mapModalLabel">内容製品編集</h5>
          <% else %>
            <h5 class="modal-title" id="mapModalLabel"><%= product.name %></h5>
          <% end %>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <% if @editable %>
          <div class="modal-body">
            <%= form_for(:sales_product_relation, url: edit_sales_product_relation_path) do |f| %>
              <div class="field input-group mt-1">
                <%= f.label :price, "価格",class:'input-group-prepend col-3 input-group-text' %>
                <%= f.text_field :price, class:'form-control', value: sales_product_relation.price %>
                <span class="input-group-text">💱</span>
                <%= f.label :product_id,"商品名", class:'input-group-text' %>
                <%= f.select :product_id, modif_product[sales_product_relation.id], {class:'form-control', required: true} %>
              </div>

              <%= f.hidden_field :id, value: sales_product_relation.id %>

              <div class="actions d-grid gap-2 mt-1">
                <%= f.submit "登録", class: "btn btn-primary" %>
              </div>
            <% end %>
          </div>
        <% end %>
        <div class="modal-footer">
          <% if product.image.attached? %>  
            <%= image_tag product.image, style: 'width: 100%; height: auto;', class:"rounded mx-auto d-block" %>
          <% else %>
            <h5>写真無し</h5>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>